[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[[redirects]]
  from = "/generate-response"
  to = "/api/generate-response"
  status = 200

[[redirects]]
  from = "/classify-image"
  to = "/api/classify-image"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
